hmrc/ios-swiftui-components

SUICompanionApp/SUICompanionApp.xcodeproj/project.pbxproj, SUICompanionApp/SUICompanionApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, SUICompanionApp/SUICompanionApp/ContentView.swift, Sources/SUIComponents/Atoms/Button+HMRC.swift, Sources/SUIComponents/Atoms/NSAttributedString+HMRC.swift, Sources/SUIComponents/Misc/Handlers.swift, Sources/SUIComponents/Molecules/StatusView.swift
* chore/status-view - adding status view
* chore/status-view - updating companion app
* chore/status-view - cleanup
Co-authored-by: tendai-moffatt <38880662+tendai-moffatt@users.noreply.github.com>
=> Chore/status view (#2)

SUICompanionApp/SUICompanionApp/Molecules/ExampleMolecules.swift, SUICompanionApp/SUICompanionApp/Molecules/MoleculesView.swift, Sources/SUIComponents/Helpers/Extensions/View+HMRC.swift, Sources/SUIComponents/Molecules/InsetView.swift
=> [HMA-4857] Inset View

SUICompanionApp/SUICompanionApp/Atoms/AtomsView.swift, SUICompanionApp/SUICompanionApp/Atoms/ExampleAtoms.swift, SUICompanionApp/SUICompanionApp/Molecules/ExampleMolecules.swift, SUICompanionApp/SUICompanionApp/Molecules/MoleculesView.swift, Sources/SUIComponents/Atoms/ImageAligningHStack.swift, Sources/SUIComponents/Molecules/IconButtonView.swift
=> [HMA-4860] Icon Button View

SUICompanionApp/SUICompanionApp/Examples/ExampleImages.swift, SUICompanionApp/SUICompanionApp/Organisms/ExampleOrganisms.swift, Sources/SUIComponents/Atoms/Button+HMRC.swift, Sources/SUIComponents/Atoms/Text+HMRC.swift, Sources/SUIComponents/Helpers/Extensions/Decimal+Components.swift, Sources/SUIComponents/Helpers/Fonts/Font+HMRC.swift, Sources/SUIComponents/Molecules/HeadlineCardView.swift
https://user-images.githubusercontent.com/3192947/140918825-f749a184-64d1-4cc4-98ae-de2e5b832833.mov
https://jira.tools.tax.service.gov.uk/browse/HMA-4865
=> [HMA-4865] - Headline Card View

SUICompanionApp/SUICompanionApp/Molecules/ExampleMolecules.swift, SUICompanionApp/SUICompanionApp/Organisms/ExampleOrganisms.swift, SUICompanionApp/SUICompanionApp/Organisms/OrganismsView.swift, Sources/SUIComponents/Molecules/IconButtonView.swift, Sources/SUIComponents/Organisms/IconButtonCardView.swift
=> [HMA-4868] IconButtonCardView

SUICompanionApp/SUICompanionApp/Organisms/ExampleOrganisms.swift, SUICompanionApp/SUICompanionApp/Organisms/OrganismsView.swift, Sources/SUIComponents/Atoms/Button+HMRC.swift, Sources/SUIComponents/Organisms/InformationMessageCard+ButtonStyles.swift, Sources/SUIComponents/Organisms/InformationMessageCard.swift
- Ticket -> [HMA-4870](https://jira.tools.tax.service.gov.uk/browse/HMA-4870)
=> [HMA-4870] Info message card

Sources/SUIComponents/Atoms/Button+HMRC.swift, Sources/SUIComponents/Helpers/Colours/SemanticColors.swift
Fixes some of the QA issues found in https://jira.tools.tax.service.gov.uk/browse/HMA-6369
=> [HMA-6369] correct layout and colours

SUICompanionApp/SUICompanionApp/Organisms/ExampleOrganisms.swift, Sources/SUIComponents/Organisms/EditableListView.swift
Accessibility fixes based on feedback from QA
=> [HMA-6087] Updated Accessibility

CHANGELOG.md, Sources/SUIComponents/Organisms/EditableListView.swift
Forgot a line of code.
I've also reset the Changelog so that I can do the first proper release
=> [HMA-6087] Added missing line

CHANGELOG.md, SUICompanionApp/SUICompanionApp/Organisms/ExampleOrganisms.swift, Sources/SUIComponents/Organisms/DonutChartView.swift, Sources/SUIComponents/Organisms/PAYEEmploymentMockupView.swift
- HMA-6218: Fix for moving shapes on orientation change
- HMA-6218: Removed debug frame
- HMA-6218: Refactored pie maths out of component
- HMA-6218: Added public to convertToSliceDetails
- HMA-6218: public modifier on slice details vars
=> HMA 6218 donut ni

CHANGELOG.md, Sources/SUIComponents/Organisms/DonutChartView.swift, Sources/SUIComponents/Organisms/PAYEEmploymentMockupView.swift
- HMA-6218: Removed conflicting animations
- HMA-6218: Updated changelog
=> HMA-6218: Removed conflicting animations from donut

CHANGELOG.md, SUICompanionApp/SUICompanionApp/Molecules/ExampleMolecules.swift, SUICompanionApp/SUICompanionApp/Molecules/MoleculesView.swift, Sources/SUIComponents/Molecules/IconButtonWithDisclosureView.swift
Add IconButtonWithDisclosureView molecule
=> Add IconButtonWithDisclosureView molecule

CHANGELOG.md
=> Release 1.6.5

CHANGELOG.md
=> Update changelog for release 1.6.6

CHANGELOG.md, Sources/SUIComponents/Atoms/CustomButton.swift
Add isButton trait to CustomButton
=> Add isButton trait to CustomButton

CHANGELOG.md
=> Update changelog for release 1.10.1

CHANGELOG.md, Sources/SUIComponents/Atoms/CustomButton.swift, Sources/SUIComponents/Molecules/SelectRowView.swift
[HMA-7598] Fixed VoiceOver selection on `SelectRowView`
=> [HMA-7598] Fixed VoiceOver selection on `SelectRowView`

CHANGELOG.md
=> Release 1.11.2

CHANGELOG.md, Sources/SUIComponents/Helpers/ViewModifiers/OptionalAccessibilityIdentifier.swift, Sources/SUIComponents/Organisms/MenuPanelRowView.swift
Fixed accessibilityIdentifier and trait on `MenuPanelRowView`
=> Fixed accessibilityIdentifier and trait on `MenuPanelRowView`

CHANGELOG.md
=> Release 1.11.3

CHANGELOG.md
=> Update changelog for release 1.12.0

CHANGELOG.md, SUIComponents.xcodeproj/project.pbxproj, Sources/SUIComponents/Molecules/IconButtonWithDisclosureView.swift
I have made some updates to the SUIComponent project to get it to build again, also
I have replaced the Drag Gesture on the component with this:
```
._onButtonGesture(pressing: { pressing in
selected = pressing
}, perform: {
model.handler()
})
```
I think this is a private function so I am wondering if this is acceptable or not?
The alternative is `.onTapGesture {}` which would not give us a "touch down" state for highlighting / selecting the row
The old drag gesture conflicts with the scrolling of the parent scroll view
=> HMA-8581 fixed IconButtonWithDisclosureView scrolling behaviour

CHANGELOG.md, Sources/SUIComponents/Molecules/IconButtonView.swift, Sources/SUIComponents/Organisms/MiniAdvertCardView.swift
fixed scrolling issue for `MiniAdvertCardView` and `IconButtonView`
=> HMA-7962-bug-fix-scrolling-issues

CHANGELOG.md, Sources/SUIComponents/Organisms/InformationMessageCard.swift
Added more granular accessibility labels to info message card
=> Improved info message card accessibility

CHANGELOG.md, SUICompanionApp/SUICompanionApp/Molecules/ExampleMolecules.swift, Sources/SUIComponents/Molecules/SecureInputView.swift
Here is my handover.  SUIComponent needs releasing to 1.17.4 I made a change with accessibility in 
SecureInputView.
Update branch HMA-8896 to use this version of SUIComponent. confirm that the change is in the branch are correct
by running the test `test_pinEntry()` in IntegrationTest LoginTestV2.
Once that is ok, PR and merge HMA-8896 into HMA-8898 then everything should be ok!
When testing the new pin, there are 5 places you need to do the `true || feature.isEnabled(Features.devNewPinScreen)`
3 are in LoginPinViewController (line 129,167,207) and 2 in LoginPinViewBuilder ( line 42, 106)
=> release 1.17.4 candidate
